
export class Jsondata {
    static headerLinks = [
        { name: "Home", link: "/" },
        { name: "About", link: "/about" },
        { name: "Product", link: "/products" },
        { name: "Blogs", link: "/blogs" },
        { name: "Contact", link: "/contact" },
    ];

    static aboutData = [
        {
            title: "Mission",
            description: "To grab opportunities through market exploration and analysis aiming for viable connectivity & network. To create trust & commitment amongst stakeholders and customers through quality & efficiency. To explore newness & unique ideas through modern research and development for product diversification and business expansion.",
            height: '300px',
            padding: "3rem 4rem"
        },
        {
            title: "Vision",
            description: `In the era of the Fourth and Fifth Industrial Revolution, the growing importance of biodegradable and non-disposable products due to climate Change and globalization has extensively driven customer’s mindset and made psychological U turn to heathy environment aiming for a healthier life. Eco Oasis Limited always dreamed to "sail beyond the sunset" to bridge between Customer’s choice, life style and healthy mindset. On this note, Eco Oasis Limited is endeavoring to source and produce eco-friendly products like Jute products, diversified jute products, handicrafts, Bamboo handicraft, agro-based organic products and post supply services to meet customized satisfaction. Started journey in 2021 with a mission to ensure Healthier Quality and on-time delivery is the commitment while the competitive price is the key strength of the Company Policy.`,
            height: '385px',
            padding: "3rem 2.2rem"
        },
        {
            title: "Message",
            description: "Shareholder’s knowledge, skills, customized mindset, innovative thinking widened in the field of Merchandising, Operations, Human Capital management, enterprise project management, and logistics service have broadened the scope to meet customized demand and deal the business in befitting manner.  Eco Oasis wants to be a true partner instead of a profit aiming entity and wants to build a long-term business association towards its vision.",
            height: '300px',
            padding: "3rem 3rem"
        },
    ]

    static blogsData = [
        {
            image: "/images/Group46.png",
            category: "Jute",
            redingDuration: "5 min read",
            title: "Simple Jute products to boost your ambient system"
        },
        {
            image: "/images/Group47.png",
            category: "Jute",
            redingDuration: "5 min read",
            title: "Simple Jute products to boost your ambient system"
        },
        {
            image: "/images/Group48.png",
            category: "Jute",
            redingDuration: "5 min read",
            title: "Simple Jute products to boost your ambient system"
        },

    ]

    static blogsTrendingData = [
        {
            image: "/images/Group23.png",
            title: "Fruit juices to boost your immune",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        },
        {
            image: "/images/Group24.png",
            title: "Juice variations using avocado",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        },
        {
            image: "/images/Group25.png",
            title: "Simple recipe strawberry juice",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        },

    ]

    static productCategories = [
        {
            id: 1,
            category: "Jute",
            image: "/images/jute.JPG",
            url: "jute"
        },
        {
            id: 2,
            category: "Leather",
            image: "/images/leather.png",
            url: "leather"
        },
        {
            id: 3,
            category: "Basket",
            image: "/images/basket.jpeg",
            url: "basket"
        },
        {
            id: 4,
            category: "Accessories",
            image: "/images/accessories.JPG",
            url: "accessories"
        },
    ]

    static products = [
        {
            id: 1,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Shopping Bag type 1",
            image: "https://i.ibb.co/hBz16J6/1-removebg-preview.jpg",
        },
        {
            id: 2,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Shopping Bag type 2",
            image: "https://i.ibb.co/XY8YGj5/2-removebg-preview.jpg",
        },
        {
            id: 3,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Shopping Bag type 3",
            image: "https://i.ibb.co/8x1psDj/3-removebg-preview.jpg",
        },
        {
            id: 4,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Shopping Bag type 4",
            image: "https://i.ibb.co/5R4ztXQ/4-removebg-preview.jpg",
        },
        {
            id: 5,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Shopping Bag type 5",
            image: "https://i.ibb.co/stJThCL/5-removebg-preview.jpg",
        },
        {
            id: 6,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Shopping Bag type 6",
            image: "https://i.ibb.co/8nCxqdQ/6-1-removebg-preview.jpg",
        },
        {
            id: 7,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Shopping Bag type 7",
            image: "https://i.ibb.co/hVbBKPT/6-removebg-preview.jpg",
        },
        {
            id: 8,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 1",
            image: "https://i.ibb.co/r5fTTVc/1-removebg-preview.jpg",
        },
        {
            id: 9,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 2",
            image: "https://i.ibb.co/XyCqPF3/2-removebg-preview.jpg",
        },
        {
            id: 10,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 3",
            image: "https://i.ibb.co/StS3MgH/3-removebg-preview.jpg",
        },
        {
            id: 11,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 4",
            image: "https://i.ibb.co/s2QQT3S/4-removebg-preview.jpg",
        },
        {
            id: 12,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 5",
            image: "https://i.ibb.co/CBF1D73/5-removebg-preview.jpg",
        },
        {
            id: 13,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 6",
            image: "https://i.ibb.co/W6YNfkP/6-removebg-preview.jpg",
        },
        {
            id: 14,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 1",
            image: "https://i.ibb.co/thTf6pg/1-removebg-preview.jpg",
        },
        {
            id: 15,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 2",
            image: "https://i.ibb.co/kQQLR5Y/2-removebg-preview.jpg",
        },
        {
            id: 16,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 3",
            image: "https://i.ibb.co/HxR4b4Z/3-removebg-preview.jpg",
        },
        {
            id: 17,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 4",
            image: "https://i.ibb.co/X5FPMDL/4-removebg-preview.jpg",
        },
        {
            id: 18,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 5",
            image: "https://i.ibb.co/0Vk6sbh/5-removebg-preview.jpg",
        },
        {
            id: 19,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 6",
            image: "https://i.ibb.co/3cKTPYH/6-removebg-preview.jpg",
        },
        {
            id: 20,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 1",
            image: "https://i.ibb.co/cJD6ynL/1-removebg-preview.jpg",
        },
        {
            id: 21,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 2",
            image: "https://i.ibb.co/dcmqfp9/2-removebg-preview.jpg",
        },
        {
            id: 22,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 3",
            image: "https://i.ibb.co/5n73gT7/3-removebg-preview.jpg",
        },
        {
            id: 23,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 4",
            image: "https://i.ibb.co/KG0W4cL/6-removebg-preview.jpg",
        },
        {
            id: 24,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 5",
            image: "https://i.ibb.co/4psTFgH/4-removebg-preview.jpg",
        },
        {
            id: 25,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 6",
            image: "https://i.ibb.co/FYQJRhq/5-removebg-preview.jpg",
        },
        {
            id: 26,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 1",
            image: "https://i.ibb.co/Xz7dh9W/1-removebg-preview.jpg",
        },
        {
            id: 27,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 2",
            image: "https://i.ibb.co/Db5rQTw/2-removebg-preview.jpg",
        },
        {
            id: 28,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 3",
            image: "https://i.ibb.co/FDPQ8Jp/5-removebg-preview.jpg",
        },
        {
            id: 29,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 4",
            image: "https://i.ibb.co/85wxpVH/EOL-Belt-001-removebg-preview.jpg",
        },
        {
            id: 30,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 5",
            image: "https://i.ibb.co/Rbn1wHS/EOL-Belt-004-removebg-preview.jpg",
        },
        {
            id: 31,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 6",
            image: "https://i.ibb.co/nQpwJ63/EOL-Belt-014-removebg-preview.jpg",
        },
        {
            id: 32,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 1",
            image: "https://i.ibb.co/17B68jV/1-removebg-preview.jpg",
        },
        {
            id: 33,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 2",
            image: "https://i.ibb.co/m9SgHW3/2-removebg-preview.jpg",
        },
        {
            id: 34,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 3",
            image: "https://i.ibb.co/YdzWbTW/3-removebg-preview.jpg",
        },
        {
            id: 35,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 4",
            image: "https://i.ibb.co/jH86bvk/4-1-removebg-preview.jpg",
        },
        {
            id: 36,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 5",
            image: "https://i.ibb.co/YP9nk1z/4-2-removebg-preview.jpg",
        },
        {
            id: 37,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 6",
            image: "https://i.ibb.co/HrZyvKr/4-3-removebg-preview.jpg",
        },
        {
            id: 38,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 1",
            image: "https://i.ibb.co/pbr45NM/IMG-6432-removebg-preview.jpg",
        },
        {
            id: 39,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 2",
            image: "https://i.ibb.co/3rxFBGH/IMG-7009-Copy-removebg-preview.jpg",
        },
        {
            id: 40,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 3",
            image: "https://i.ibb.co/NjCZcPK/IMG-7822-removebg-preview.jpg",
        },
        {
            id: 41,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 4",
            image: "https://i.ibb.co/6XVLGWG/IMG-7823-removebg-preview.jpg",
        },
        {
            id: 42,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 5",
            image: "https://i.ibb.co/ZxbZtpb/IMG-7825-removebg-preview.jpg",
        },
        {
            id: 43,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 6",
            image: "https://i.ibb.co/qxY3py7/IMG-7904-removebg-preview.jpg",
        },
        {
            id: 44,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 1",
            image: "https://i.ibb.co/mRD3RfP/1-removebg-preview.jpg",
        },
        {
            id: 45,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 2",
            image: "https://i.ibb.co/Km5pd1z/2-removebg-preview.jpg",
        },
        {
            id: 46,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 3",
            image: "https://i.ibb.co/nPKSpbq/3-removebg-preview.jpg",
        },
        {
            id: 47,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 4",
            image: "https://i.ibb.co/zQsGFrk/4-removebg-preview.jpg",
        },
        {
            id: 48,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 5",
            image: "https://i.ibb.co/KjdVY6t/5-removebg-preview.jpg",
        },
        {
            id: 49,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 6",
            image: "https://i.ibb.co/DfvY62Y/6-removebg-preview.jpg",
        },
        {
            id: 50,
            category: "Leather",
            subcategory: "Office bags",
            name: "Office bag type 1",
            image: "https://i.ibb.co/4MzNNrB/38-removebg-preview.jpg",
        },
        {
            id: 51,
            category: "Leather",
            subcategory: "Office bags",
            name: "Office bag type 2",
            image: "https://i.ibb.co/jZT5KB3/IMG-0683-removebg-preview.jpg",
        },
        {
            id: 52,
            category: "Leather",
            subcategory: "Office bags",
            name: "Office bag type 3",
            image: "https://i.ibb.co/dt0DP5v/IMG-0697-removebg-preview.jpg",
        },
        {
            id: 53,
            category: "Leather",
            subcategory: "Office bags",
            name: "Office bag type 4",
            image: "https://i.ibb.co/TY9k524/IMG-0698-removebg-preview.jpg",
        },
        {
            id: 54,
            category: "Leather",
            subcategory: "Office bags",
            name: "Office bag type 5",
            image: "https://i.ibb.co/JcyRrGX/IMG-0705-removebg-preview.jpg",
        },
        {
            id: 55,
            category: "Leather",
            subcategory: "Office bags",
            name: "Office bag type 6",
            image: "https://i.ibb.co/J54PCr6/IMG-0708-removebg-preview.jpg",
        },
        {
            id: 56,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 1",
            image: "https://i.ibb.co/q5N4yfK/1-removebg-preview.jpg",
        },
        {
            id: 57,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 2",
            image: "https://i.ibb.co/pLJh0r2/2-removebg-preview.jpg",
        },
        {
            id: 58,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 3",
            image: "https://i.ibb.co/4t5Q7QB/3-removebg-preview.jpg",
        },
        {
            id: 59,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 4",
            image: "https://i.ibb.co/LCwM3zX/4-removebg-preview.jpg",
        },
        {
            id: 60,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 5",
            image: "https://i.ibb.co/N1MWzVQ/5-removebg-preview.jpg",
        },
        {
            id: 61,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 6",
            image: "https://i.ibb.co/DfyrLwR/6-removebg-preview.jpg",
        },
        {
            id: 62,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 7",
            image: "https://i.ibb.co/GntwC9G/7-removebg-preview.jpg",
        },
        {
            id: 63,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 8",
            image: "https://i.ibb.co/hVhRgYH/8-removebg-preview.jpg",
        },
        {
            id: 64,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 9",
            image: "https://i.ibb.co/vLKtnw4/9-removebg-preview.jpg",
        },
        {
            id: 65,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Footwear",
            image: "https://i.ibb.co/ygjrsrb/1-removebg-preview.jpg",
        },
        {
            id: 66,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Wall lamp",
            image: "https://i.ibb.co/1MPxXVD/2-removebg-preview.jpg",
        },
        {
            id: 67,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Cikka",
            image: "https://i.ibb.co/q5V1hvY/3-removebg-preview.jpg",
        },
        {
            id: 68,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Card holder type 1",
            image: "https://i.ibb.co/k0kLb0z/4-removebg-preview.jpg",
        },
        {
            id: 69,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Card holder type 2",
            image: "https://i.ibb.co/HPCdW11/5-removebg-preview.jpg",
        },
        {
            id: 70,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Card holder type 3",
            image: "https://i.ibb.co/9HDNc3b/6-removebg-preview.jpg",
        },
    ]
}
