
export class Jsondata {
    static headerLinks = [
        { name: "Home", link: "/" },
        { name: "About", link: "/about" },
        {
            name: "Product", link: "/products", category: [
                "jute", "leather", "basket", "accessories"
            ]
        },
        { name: "Blogs", link: "/blogs" },
        { name: "Contact", link: "/contact" },
    ];

    static aboutData = [
        {
            title: "Eco-Friendly Fiber Jute, Cotton etc.",
            description: "Jute is a natural eco-friendly fiber that is biodegradable, renewable, and sustainable, which makes it an eco-friendly alternative to synthetic materials. Jute plants are grown with minimal use of fertilizers and pesticides, which reduces their environmental impact. Jute is called an eco- friendly product because it has a low carbon footprint.The production of jute requires much less energy than the production of synthetic materials, and jute processing plants can use renewable energy sources like solar or wind power to minimize their carbon emissions. Jute is also considered a biodegradable material because it is made of cellulose, a natural polymer that can be broken down by environmental microorganisms.When jute products are discarded, they decompose gradually over time and turn into organic matter that can be used as fertilizer. Jute is a versatile material that can be used to make a wide range of products, from shopping bags to home decor and clothing.Jute products are durable and long - lasting, which means they do not need to be replaced as frequently as other products, reducing waste.Jute can be blended with Cotton or Cotton itself also an eco - friendly material that also has the same characteristics.",

        },
        {
            title: "Coco Husk, Cocopeat , Coco Fiber, Coir, etc",
            description: `The environmental importance of coconut husk, coir, and cocopeat lies in their sustainable and eco-friendly properties. These products are made from a waste product of the coconut industry, which helps to reduce waste and promote sustainability. By using these materials, we can reduce the amount of waste that would otherwise end up in landfills or be burned, which can release harmful pollutants into the air. Coconut trees are highly renewable and can produce fruit for up to 60 years, making coconut husk, coir, and cocopeat highly sustainable resources. This means that they can be harvested without depleting the resources of the environment. These products are biodegradable, which means that they can be easily decomposed by natural processes. When they are no longer useful, they break down naturally and do not leave harmful residue in the environment. Using coconut husk, coir, and cocopeat in various applications, such as gardening and horticulture, also helps to reduce the use of non-renewable and synthetic materials. This can help to reduce the environmental impact of these activities and promote more sustainable practices.`,

        },
        {
            title: "Eco Friendly Basket",
            description: `Eco-friendly baskets are a sustainable and responsible choice for those looking to make a positive impact on the environment. As more people become aware of the negative impact of single-use plastics and synthetic materials, eco-friendly baskets have become increasingly popular. The most significant advantage of eco-friendly baskets is that they are made from natural, biodegradable materials that are renewable and sustainable. For example, baskets made from Jute, Seagrass, Kashia, Bamboo, etc do not require harsh chemicals to produce and can be composted or recycled at the end of their lifespan, reducing waste and environmental pollution. It has a positive impact on local communities and economies. Many of these baskets are handmade by skilled artisans providing sustainable employment opportunities and supporting local businesses. By choosing eco-friendly baskets, consumers can contribute to the growth and development of these communities. Eco-friendly baskets offer a range of uses and benefits in our daily lives. They can be used for Planers, Laundry baskets, Pet houses, Kitchen baskets, Storage baskets, shopping, or decoration, and are often more durable and long-lasting than plastic alternatives. Eco-friendly baskets are an essential component of a sustainable lifestyle, helping to reduce waste and support sustainable practices. 
`,

        },
        {
            title: "Leather, Natural Lifestyle stuff",
            description: `Leather is a natural material that is made from the hide of various animals, including cows, sheep, and goats. It is used to make a wide range of products, from clothing and accessories to furniture and car seats. Leather has a rich history and has been used by royalty and the wealthy for centuries, which has led to a perception of leather as a premium material. Leather products have been a part of human culture and lifestyle for centuries, and they continue to remain popular due to their durability, versatility, and aesthetic appeal. Leather is a sturdy and long-lasting material that can withstand wear and tear, it is easy to clean and maintain, which makes it a practical choice for everyday use. Leather can be dyed, stamped, embossed, and molded into a variety of shapes and designs to suit every taste and style. Leather products can be casual or formal, classic or trendy, and they can be paired with a variety of outfits to create a polished, elegant look. Today’s modern customers who prefer to use Genuine leather items are more forward thinkers and careful about any health & hygiene issues that may impact adversely their lifestyle. Smart Customers now a day look forward to emphasizing the biological behavior of any commodities, and materials besides their quality and durability. We are committed to sourcing and producing genuine leather goods by ensuring proper tanning chemistry. We ensure you the genuineness of leather from our range of signature items like Men belts, Wallets, Shoes, Ladies' Hand Bags, Purses, Card Holders, jackets, Travel bags, etc.
`,

        },
    ]

    static blogsData = [
        {
            image: "https://i.ibb.co/DGr98hb/Biodegradable-Product.jpg",
            category: "Eco Oasis",
            redingDuration: "5 min read",
            title: "What is a Biodegradable product?",
            link: "https://www.facebook.com/100091847673371/posts/pfbid0vhhGLbY18XyMTnSbkczkkXUrKi3D5CmJRYHSC7s2mp35geYbmwgNcStHdf27GxVzl/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/hcTw7qw/Jute-Biodegradable-product.jpg",
            category: "Eco Oasis",
            redingDuration: "5 min read",
            title: "What is Jute and is it a Biodegradable product?",
            link: "https://www.facebook.com/100091847673371/posts/pfbid0rfz8a83QFzrjT8oeUcZgzuuPU3CgSuPWt9ykwx9iFp1iA61FCEEhPFYuhv8GpsrYl/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/Fn6RhTF/c2de28bf-9486-4ac3-9d8b-b111577ba5ac.jpg",
            category: "Eco Oasis",
            redingDuration: "5 min read",
            title: "What is an Eco-friendly product and is Jute an Eco-friendly product?",
            link: "https://www.facebook.com/100091847673371/posts/pfbid02e4c2TdgZXvtoY54X3VmwLqhZRYmWgw3uyr964RaZDxNSs6V6XxEgJjiqk29cokPil/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/rHKV9qF/Jute-Lifestyle-brand.jpg",
            category: "Eco Oasis",
            redingDuration: "5 min read",
            title: "Why Eco-friendly & Biodegradable products are getting popularity as lifestyle products.",
            link: "https://www.facebook.com/100091847673371/posts/pfbid0omJbFXBNUgkMYdHemHjGRGky7dd5auVVFrpJWe3Es4kWfwN9ws4owGDwXsrgHMul/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/cYvhskT/product-jpeg-500x500.webp",
            category: "Eco Oasis",
            redingDuration: "5 min read",
            title: "Why should modern customers use Eco-friendly & non-disposable products?",
            link: "https://www.facebook.com/100091847673371/posts/pfbid0NBrY4vmk3U7aaDA3mtPLhC7McnGHDVLzep3W9pLusmYcnHdpUWzYMfZRSDLQAsbml/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/SmBLzwb/FB-IMG-1681224653408.jpg",
            category: "Eco Oasis",
            redingDuration: "5 min read",
            title: "Why Bangladeshi jute is famous around the world?",
            link: "https://www.facebook.com/100091847673371/posts/pfbid029LGzC6JCddbKRMkgcBDxPDS6n2QjNEMnavxZeMKsDsPxhbXgvZQKhD7jjMLewJ5El/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/zRrYFGM/q.png",
            category: "Eco Oasis",
            redingDuration: "5 min read",
            title: "Why Jute is called “Golden Fiber” in Bangladesh?",
            link: "https://www.facebook.com/100091847673371/posts/pfbid02b6VMAEDkRgA6BtwnVoKS7wLA5Gtbp6x3UBzBnvWihfz3jJFsu3GSuwXeVT8AN4rhl/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/28GDrPQ/Jute-Sustainable.jpg",
            category: "Eco Oasis",
            redingDuration: "5 min read",
            title: "Why is Jute made products getting popularity around the world instead of plastic?",
            link: "https://www.facebook.com/100091847673371/posts/pfbid024oqwK5fmmA4CKnxdP93RoLGp4cz6qkzkRPxm27vgaoaUm4LnvSzp7vWJeSirUXJ7l/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/7QxZQfT/FB-IMG-1681224432417.jpg",
            category: "Eco Oasis",
            redingDuration: "5 min read",
            title: "Why Eco Oasis Limited is focused on Eco-friendly & Biodegradable Products?",
            link: "https://www.facebook.com/100091847673371/posts/pfbid02Kj1PKrKU9EvsL2eNVa91rKeKw6PvQmEA3ZEZx9cf5VnJ98MuikrQxguFhZZaQjZDl/?mibextid=cr9u03"
        },
    ]

    static blogsTrendingData = [
        {
            image: "https://i.ibb.co/2cc7MYp/green-product-1200x669.webp",
            title: "Why we should focus on Eco Friendly & Biodegradable Products?",
            description: "There are several reasons why we should focus on eco-friendly and biodegradable products",
            link: "https://www.facebook.com/100091847673371/posts/pfbid04BoiTRWJq8rkqqwPXGVJiaLRuwpoJY1SUhVr9Qey6Sdm49VjuXo6enWjTf16ER4Ul/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/RCFffMZ/JUTE-27-11-19.jpg",
            title: "What is jute fiber? How it is originated & cultivated?",
            description: "Jute fiber is a natural vegetable fiber that is harvested from the stem of the jute plant",
            link: "https://www.facebook.com/100091847673371/posts/pfbid034iGrkkvCpVY3pkcBhMREJAnQGFyWwBSSXdKQ8WAUAoDGWhPBBoX94CjpRQKDuLzWl/?mibextid=cr9u03"
        },
        {
            image: "https://i.ibb.co/m6S7XHv/Diversified-Jute-Products.webp",
            title: "What kind of lifestyle products are made out of jute fiber?",
            description: "Jute is a versatile and eco-friendly material that can be used to create a wide range of lifestyle products",
            link: "https://www.facebook.com/100091847673371/posts/pfbid0tYydB9dNvvYGkiKZCwhgmwJyhBmcqgA7JD72My5owuBm5JtDjGM8rQ3S7von9tCrl/?mibextid=cr9u03"
        },

    ]

    static productCategories = [
        {
            id: 1,
            title: "Jute, Cotton",
            category: "Jute",
            image: "/images/jutecat.jpeg",
            url: "jute"
        },
        {
            id: 2,
            title: "Cocopeat, Coco Husk & Coir",
            category: "Coco",
            image: "https://i.ibb.co/5W1Xnzy/Category-Picture.jpg",
            url: "coco"
        },
        {
            id: 3,
            title: "Eco-Friendly Basket",
            category: "Basket",
            image: "/images/basket.jpeg",
            url: "basket"
        },
        {
            id: 4,
            title: "Leather Stuff",
            category: "Leather",
            image: "/images/leather.png",
            url: "leather"
        },
        {
            id: 5,
            title: "Accessories",
            category: "Accessories",
            image: "https://img3.exportersindia.com/product_images/bc-full/2020/9/7152048/mens-travel-wallet-1599121067-5573013.jpeg",
            url: "accessories"
        },

    ]

    static products = [
        {
            id: 1,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Bag type 1",
            info: "Natural Jute with Lamination. Printed.",
            image: "https://i.ibb.co/hBz16J6/1-removebg-preview.jpg",
        },
        {
            id: 2,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Bag type 2",
            info: "Natural Jute with Lamination. Printed.",
            image: "https://i.ibb.co/XY8YGj5/2-removebg-preview.jpg",
        },
        {
            id: 3,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Bag type 3",
            info: "Natural Jute Lamination.",
            image: "https://i.ibb.co/8x1psDj/3-removebg-preview.jpg",
        },
        {
            id: 4,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Bag type 4",
            info: "Natural Jute Net.",
            image: "https://i.ibb.co/5R4ztXQ/4-removebg-preview.jpg",
        },
        {
            id: 5,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Bag type 5",
            info: "Cotton Canvas, Printed.",
            image: "https://i.ibb.co/stJThCL/5-removebg-preview.jpg",
        },
        {
            id: 6,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Bag type 6",
            info: "Natural Jute.",
            image: "https://i.ibb.co/zSXs2sn/6-1-removebg-preview.jpg",
        },
        {
            id: 7,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Bag type 7",
            info: "Woven Fabric.",
            image: "https://i.ibb.co/hVbBKPT/6-removebg-preview.jpg",
        },
        {
            id: 8,
            category: "Jute",
            subcategory: "Shopping Bag",
            name: "Bag type 8",
            info: "Cotton Canvas, Printed.",
            image: "https://i.ibb.co/t21mMZw/8.jpg",
        },

        {
            id: 9,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 1",
            info: "Natural Jute Braided, Handmade flower.",
            image: "https://i.ibb.co/r5fTTVc/1-removebg-preview.jpg",
        },
        {
            id: 10,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 2",
            info: "Natural Jute Macramé.",
            image: "https://i.ibb.co/XyCqPF3/2-removebg-preview.jpg",
        },
        {
            id: 11,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 3",
            info: "Natural Jute Fabric, Seashell, Flower Handwork.",
            image: "https://i.ibb.co/StS3MgH/3-removebg-preview.jpg",
        },
        {
            id: 12,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 4",
            info: "Jute, Zipper, Inner chamber, Metal Handle.",
            image: "https://i.ibb.co/s2QQT3S/4-removebg-preview.jpg",
        },
        {
            id: 13,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 5",
            info: "Jute Braided, Handwork Flower, Macramé Handle.",
            image: "https://i.ibb.co/CBF1D73/5-removebg-preview.jpg",
        },
        {
            id: 14,
            category: "Jute",
            subcategory: "Ladies fashionable bag",
            name: "Bag type 6",
            info: "Jute Fabric, Handwork Flower.",
            image: "https://i.ibb.co/cwJvd9h/6.jpg",
        },
        {
            id: 15,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 1",
            info: "Natural/Colored Jute Braided.",
            image: "https://i.ibb.co/thTf6pg/1-removebg-preview.jpg",
        },
        {
            id: 16,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 2",
            info: "Natural/Colored Jute Braided.",
            image: "https://i.ibb.co/kQQLR5Y/2-removebg-preview.jpg",
        },
        {
            id: 17,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 3",
            info: "Natural/Colored Jute Braided.",
            image: "https://i.ibb.co/HxR4b4Z/3-removebg-preview.jpg",
        },
        {
            id: 18,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 4",
            info: "Natural/Colored Jute Braided.",
            image: "https://i.ibb.co/X5FPMDL/4-removebg-preview.jpg",
        },
        {
            id: 19,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 5",
            info: "Jute Rope, Medicated.",
            image: "https://i.ibb.co/0Vk6sbh/5-removebg-preview.jpg",
        },
        {
            id: 20,
            category: "Jute",
            subcategory: "Rug",
            name: "Rug type 6",
            info: "Jute Braided, Big Floor mat.",
            image: "https://i.ibb.co/3cKTPYH/6-removebg-preview.jpg",
        },
        {
            id: 21,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 1",
            info: "Natural/Colored Jute Braided.",
            image: "https://i.ibb.co/cJD6ynL/1-removebg-preview.jpg",
        },
        {
            id: 22,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 2",
            info: "Natural Jute Braided.",
            image: "https://i.ibb.co/dcmqfp9/2-removebg-preview.jpg",
        },
        {
            id: 23,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 3",
            info: "Plum Fiber.",
            image: "https://i.ibb.co/5n73gT7/3-removebg-preview.jpg",
        },
        {
            id: 24,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 4",
            info: "Natural Jute Fabric.",
            image: "https://i.ibb.co/KG0W4cL/6-removebg-preview.jpg",
        },
        {
            id: 25,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 5",
            info: "Natural Jute Braided.",
            image: "https://i.ibb.co/4psTFgH/4-removebg-preview.jpg",
        },
        {
            id: 26,
            category: "Jute",
            subcategory: "Placemats",
            name: "Placemat type 6",
            info: "Natural/Beached Jute Braided.",
            image: "https://i.ibb.co/FYQJRhq/5-removebg-preview.jpg",
        },

        {
            id: 27,
            category: "Coco Peat and Coir",
            subcategory: "Coco Peat and Coir",
            name: "Cocopeat",
            image: "https://i.ibb.co/dtRdPY2/1-Cocco-Peat.jpg",
        },
        {
            id: 28,
            category: "Coco Peat and Coir",
            subcategory: "Coco Peat and Coir",
            name: "Coco Fibre",
            image: "https://i.ibb.co/Y8ww90k/2-Coco-Fibre.jpg",
        },
        {
            id: 29,
            category: "Coco Peat and Coir",
            subcategory: "Coco Peat and Coir",
            name: "Coco Husk",
            image: "https://i.ibb.co/7ywPqTm/3-Coco-Husk.png",
        },
        {
            id: 30,
            category: "Coco Peat and Coir",
            subcategory: "Coco Peat and Coir",
            name: "Coco Poles",
            image: "https://i.ibb.co/JxNqbWQ/4-Coco-Pols.png",
        },
        {
            id: 31,
            category: "Coco Peat and Coir",
            subcategory: "Coco Peat and Coir",
            name: "Coir Pot",
            image: "https://i.ibb.co/qMW9B06/5-Coir-Pot.png",
        },
        {
            id: 32,
            category: "Coco Peat and Coir",
            subcategory: "Coco Peat and Coir",
            name: "Coir Weed Mat",
            image: "https://i.ibb.co/k4xLF0S/6-Coir-Weed-Mat.jpg",
        },
        {
            id: 33,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 1",
            info: "Seagrass with Poly.",
            image: "https://i.ibb.co/q5N4yfK/1-removebg-preview.jpg",
        },
        {
            id: 34,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 2",
            info: "Natural and Color Jute Braided.",
            image: "https://i.ibb.co/pLJh0r2/2-removebg-preview.jpg",
        },
        {
            id: 35,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 3",
            info: "Seagrass, Recycle Fabric.",
            image: "https://i.ibb.co/4t5Q7QB/3-removebg-preview.jpg",
        },
        {
            id: 36,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 4",
            info: "Seagrass.",
            image: "https://i.ibb.co/LCwM3zX/4-removebg-preview.jpg",
        },
        {
            id: 37,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 5",
            info: "Seagrass, Recycle Fabric.",
            image: "https://i.ibb.co/N1MWzVQ/5-removebg-preview.jpg",
        },
        {
            id: 38,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 6",
            info: "Segrass with Metal Frame.",
            image: "https://i.ibb.co/DfyrLwR/6-removebg-preview.jpg",
        },
        {
            id: 39,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 7",
            info: "Kashia.",
            image: "https://i.ibb.co/GntwC9G/7-removebg-preview.jpg",
        },
        {
            id: 40,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 8",
            info: "Natural and Color Jute.",
            image: "https://i.ibb.co/hVhRgYH/8-removebg-preview.jpg",
        },
        {
            id: 41,
            category: "Baskets",
            subcategory: "Basket Items",
            name: "Basket type 9",
            info: "Seagrass.",
            image: "https://i.ibb.co/vLKtnw4/9-removebg-preview.jpg",
        },
        {
            id: 42,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 1",
            info: "Plain Leather.",
            image: "https://i.ibb.co/Xz7dh9W/1-removebg-preview.jpg",
        },
        {
            id: 43,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 2",
            info: "Plain Leather.",
            image: "https://i.ibb.co/Db5rQTw/2-removebg-preview.jpg",
        },
        {
            id: 44,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 3",
            info: "Plain Leather.",
            image: "https://i.ibb.co/FDPQ8Jp/5-removebg-preview.jpg",
        },
        {
            id: 45,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 4",
            info: "Emboss Leather.",
            image: "https://i.ibb.co/85wxpVH/EOL-Belt-001-removebg-preview.jpg",
        },
        {
            id: 46,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 5",
            info: "Printed Leather.",
            image: "https://i.ibb.co/Rbn1wHS/EOL-Belt-004-removebg-preview.jpg",
        },
        {
            id: 47,
            category: "Leather",
            subcategory: "Belts",
            name: "Belt type 6",
            info: "Design Leather.",
            image: "https://i.ibb.co/nQpwJ63/EOL-Belt-014-removebg-preview.jpg",
        },
        {
            id: 48,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 1",
            image: "https://i.ibb.co/17B68jV/1-removebg-preview.jpg",
        },
        {
            id: 49,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 2",
            image: "https://i.ibb.co/m9SgHW3/2-removebg-preview.jpg",
        },
        {
            id: 50,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 3",
            image: "https://i.ibb.co/YdzWbTW/3-removebg-preview.jpg",
        },
        {
            id: 51,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 4",
            image: "https://i.ibb.co/jH86bvk/4-1-removebg-preview.jpg",
        },
        {
            id: 52,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 5",
            image: "https://i.ibb.co/YP9nk1z/4-2-removebg-preview.jpg",
        },
        {
            id: 53,
            category: "Leather",
            subcategory: "Wallets",
            name: "Wallet type 6",
            image: "https://i.ibb.co/HrZyvKr/4-3-removebg-preview.jpg",
        },
        {
            id: 54,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 1",
            info: "Split Leather Natural/Color.",
            image: "https://i.ibb.co/pbr45NM/IMG-6432-removebg-preview.jpg",
        },
        {
            id: 55,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 2",
            info: "Split Leather.",
            image: "https://i.ibb.co/3rxFBGH/IMG-7009-Copy-removebg-preview.jpg",
        },
        {
            id: 56,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 3",
            info: "Split Leather Color.",
            image: "https://i.ibb.co/NjCZcPK/IMG-7822-removebg-preview.jpg",
        },
        {
            id: 57,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 4",
            info: "Split Leather Color.",
            image: "https://i.ibb.co/6XVLGWG/IMG-7823-removebg-preview.jpg",
        },
        {
            id: 58,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 5",
            info: "Split Leather.",
            image: "https://i.ibb.co/ZxbZtpb/IMG-7825-removebg-preview.jpg",
        },
        {
            id: 59,
            category: "Leather",
            subcategory: "Gloves",
            name: "Gloves type 6",
            info: "Split Leather, Velcro.",
            image: "https://i.ibb.co/qxY3py7/IMG-7904-removebg-preview.jpg",
        },
        {
            id: 60,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 1",
            image: "https://i.ibb.co/mRD3RfP/1-removebg-preview.jpg",
        },
        {
            id: 61,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 2",
            image: "https://i.ibb.co/Km5pd1z/2-removebg-preview.jpg",
        },
        {
            id: 62,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 3",
            image: "https://i.ibb.co/nPKSpbq/3-removebg-preview.jpg",
        },
        {
            id: 63,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 4",
            image: "https://i.ibb.co/zQsGFrk/4-removebg-preview.jpg",
        },
        {
            id: 64,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 5",
            image: "https://i.ibb.co/KjdVY6t/5-removebg-preview.jpg",
        },
        {
            id: 65,
            category: "Leather",
            subcategory: "Ladies bags",
            name: "Ladies bag type 6",
            image: "https://i.ibb.co/DfvY62Y/6-removebg-preview.jpg",
        },
        {
            id: 66,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Jute Sleeper.",
            info: "Natural Jute.",
            image: "https://i.ibb.co/ygjrsrb/1-removebg-preview.jpg",
        },
        {
            id: 67,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Wall lamp",
            info: "Jute and Electric Items.",
            image: "https://i.ibb.co/1MPxXVD/2-removebg-preview.jpg",
        },
        {
            id: 68,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Cikka",
            info: "Natural Jute Braid.",
            image: "https://i.ibb.co/q5V1hvY/3-removebg-preview.jpg",
        },
        {
            id: 69,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Card holder type 1",
            info: "Leather.",
            image: "https://i.ibb.co/k0kLb0z/4-removebg-preview.jpg",
        },
        {
            id: 70,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Card holder type 2",
            info: "Leather, Metal Button.",
            image: "https://i.ibb.co/HPCdW11/5-removebg-preview.jpg",
        },
        {
            id: 71,
            category: "Accessories",
            subcategory: "Accessories & others",
            name: "Card holder type 3",
            info: "Leather, Zipper.",
            image: "https://i.ibb.co/9HDNc3b/6-removebg-preview.jpg",
        },
    ]
}
